name: Release

on:
  push:
    branches:
      - main  # The branch containing your code
    tags:
      - 'v*'

jobs:
  build:
    name: Build and Release
    runs-on: ubuntu-latest

    steps:
    - name: Check out code
      uses: actions/checkout@v2

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.22

    - name: Build
      run: cd src && make all


    - name: Upload Artifacts
      uses: actions/upload-artifact@v2
      with:
        path: src/bin/*

    # - name: Create Release
    #   if: startsWith(github.ref, 'refs/tags/')
    #   uses: softprops/action-gh-release@v2
    #   with:
    #     files: |
    #       sshtows-${{ matrix.binary-suffix }}
    #   env:
    #     GITHUB_TOKEN: ${{ secrets.TOKEN }}
